### ISSUE TITLE
Function "GetBalance" doesn't working.

### ISSUE THREAD

**Issue by DraugHrenoviy** [ARitz-Cracker/ARCBank#7]
I tried to use this function on my IceHUD.

```
149 | if icehud.isDarkRP --[[&& ply:getDarkRPVar("money")]]-- 
150 | then
151 |	local glo = ARCBank.GetBalance(ply, "", function(errorcode, money) end)
<•••>
163 |	draw.SimpleText( glo )
```

But this function doesn't working.

`[hud] addons/hud/lua/autorun/client/ice_hud.lua:163: attempt to concatenate local 'glo' (a nil value)`

What i did wrong and what can i do?

**Comment by HexSilenceX** [comment]
I'm not one of the developers but that looks like a ice_hud problem, Idont have a problem with my ARCBank

**Comment by HexSilenceX** [comment]
and have you installed "https://steamcommunity.com/workshop/filedetails/?id=1647685281"

**Comment by ARitz-Cracker** [comment]
Hi there. Sorry for not responding to ARCBank issues, I haven't played GMod at all in the past few years and I'm unable to properly maintain the addons.

This appears to be a misconception with how the ARCBank.GetBalance function works. It doesn't return anything, as the information isn't readily available, in the context of the client side, has to ask the server what the balance is which takes time. You have to pass a function which is then called in the future. Also, the way you have it set up, it appears that you are attempting to retrieve the balance _every frame_ this isn't a good idea.

The best solution would be to listen to the `ARCBank_OnTransaction` server side event hook, and send the updated balance to the client when a transaction happens.
