### ISSUE TITLE
Your easteregg is giving me a headache

### ISSUE THREAD

**Issue by sword134** [ARitz-Cracker/ARCBank#8]
DELETED

**Comment by thexkey** [comment]
the code is 666666 or 666. 
Here's a video of what it will let you do:

Teleport to each ATM:

https://user-images.githubusercontent.com/24478471/134088864-4e842bfd-faf0-4b49-b552-2c1f1a1a60a2.mp4

Crash button does what it says, crashes your garry's mod.

Relocate all does this if you do it twice

https://user-images.githubusercontent.com/24478471/134088996-2345d20e-b5ab-4454-baac-7dc6b5bcb043.mp4
